[workspace]

[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "bus-mu"
version = "0.1.0"
edition = "2021"

[dependencies]
actor_framework = { path = "actor_framework" }
n64 = { path = "n64" }
