[package]
name = "vr4300"
version.workspace = true
edition = "2021"

[lib]

[features]
ui = ["egui"]

[dependencies]
modular-bitfield = { workspace = true }
egui = { workspace = true, optional = true }
common = { path = "../../common" }
