[package]
name = "n64"
version.workspace = true
edition = "2021"

[lib]

[features]
ui = ["common/ui", "actor_framework/ui"]

[dependencies]
actor_framework = { path = "../actor_framework" }
vr4300 = { path = "vr4300" }
common = { path = "../common" }
anyhow = { workspace = true }
