[package]
name = "n64"
version.workspace = true
edition = "2021"

[lib]

[dependencies]
modular-bitfield = "0.11.2"
#actor_framework = { path = "../actor_framework",  features = ["linked_list"] }
actor_framework = { path = "../actor_framework",  features = ["branchless", "linked_list"] }